site_name: SFTPGo documentation
site_url: 'https://docs.sftpgo.com'

nav:
  - index.md
  - changelog.md
  - features.md
  - 'Getting Started':
    - installation.md
    - initial-configuration.md
    - docker.md
    - 'Data provider management': data-provider.md
  - 'Tutorials':
    - "Let's Encrypt TLS Certificates": tutorials/lets-encrypt-certificate.md
    - 'Two-factor Authentication': tutorials/two-factor-authentication.md
    - tutorials/sftp-google-cloud.md
    - tutorials/eventmanager.md
    - tutorials/postgresql-s3.md
  - 'Configuration':
    - cli.md
    - config-file.md
    - env-vars.md
    - web-interfaces.md
    - 'Password Hashing': password.md
    - kms.md
  - virtual-folders.md
  - groups.md
  - roles.md
  - 'Brute force protection': defender.md
  - eventmanager.md
  - oidc.md
  - rest-api.md
  - rate-limiting.md
  - plugins.md
  - logs.md
  - metrics.md
  - 'Protocols':
    - ssh.md
    - ftp.md
    - webdav.md
  - 'Storage providers':
    - localfs.md
    - 'S3': s3.md
    - 'Google Cloud': google-cloud-storage.md
    - 'Azure Blob': azure-blob-storage.md
    - 'Data At Rest Encryption': dare.md
    - 'SFTP': sftpfs.md
    - 'HTTPFs': httpfs.md
  - 'Hooks':
    - external-auth.md
    - keyboard-interactive.md
    - dynamic-user-mod.md
    - custom-actions.md
    - 'Post-connect': post-connect-hook.md
    - 'Post-login': post-login-hook.md
    - 'Post-disconnect': post-disconnect-hook.md
    - 'Check password': check-password-hook.md
  - 'Profiling': profiling.md
  #- performance.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - mdx_truly_sane_lists

extra:
  generator: true
  social:
    - icon: material/web
      link: https://sftpgo.com
      name: SFTPGo Website
  version:
    provider: mike